version: 0.2

phases:
  pre_build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
  build:
    commands:
      - docker build --no-cache -t test -f docker/Dockerfile .
      - docker save -o test.tar test
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - test.tar
    - appspec.yml
    - deploy_scripts/*
    - nginx/**/*
    - docker/*