# 개발 서버에서 사용되는 컴포즈 설정
# Based on docker-compose.local.yml
version: '3.8'

services:
  node-server:
    # CI/CD에서 빌드된 Docker 이미지의 태그명, docker/.env에 정의되어 있음
    # 서버환경에서는 빌드된 이미지를 사용함
    image: ${PROJECT_NAME}
    # 시스템 재부팅 시에도 자동으로 컨테이너가 올라가도록 하는 설정
    restart: unless-stopped
    # 테스트를 위해서 로컬환경에서 이미지를 빌드하기 위한 설정
    # 서버환경에서는 사용되지 않음
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        INSTALL_NODEMON: "false"
    ports:
      # 서버환경에서는 1machine:1docker 이므로 고정된 서비스포트 사용
      # 서버의 nginx는 3000번 포트로 proxy 연결하도록 고정되어 있음
      - "3000:3000"
    environment:
      # 개발환경 모드로 실행
      - NODE_RUN_LEVEL=DEV
    # 일반모드로 node.js 실행
    command: [ "npm", "start" ]